server:
  port: 9521
spring:
  application:
    name: sb2-security
  redis:
    host: 192.168.110.180
    port: 6379
    password: '123456'
    database: 0
  cache:
    type: redis
  config:
    import: conf/maria-local.yml
management:
  endpoints:
    web:
      exposure:
        include: '*'