server:
  port: 9521
spring:
  application:
    name: micro-srv-a
  cache:
    type: redis
  profiles:
    active: ${app.env:154}
  config:
    import:
      - conf/${spring.profiles.active}/dataportal.yml
      - conf/${spring.profiles.active}/dataopen.yml
      - conf/${spring.profiles.active}/redis.yml


