server:
  port: 9521
spring:
  application:
    name: micro-srv-a
  cache:
    type: redis
  config:
    import: conf/mysql-local.yml,conf/redis-yoga14s.yml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    db:
      enabled: off
