spring:
  datasource:
    dataopen:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://172.21.72.158:8003/dataopen?serverTimezone=Asia/Shanghai
      username: root
      password: 'root'

mybatis:
  configuration:
    mysql:
      map-underscore-to-camel-case: on