server:
  port: 9524
spring:
  application:
    name: micro-srv-d
  config:
    import:
      - conf/mysql-dev-dataportal-154.yml
      # - conf/mysql-dev-dataopen-156.yml
      - conf/yoga14s-pgsql-local.yml
      - conf/yoga14s-mysql-local.yml
      #- conf/code01-pgsql-local.yml
      # - conf/code01-mariadb-local.yml
logging:
  level:
    org.zmz.d: debug
    org.mybatis: debug