server:
  port: 9522
spring:
  application:
    name: micro-srv-b
  config:
    import:
      # - conf/kafka-yoga14s.yml
      - conf/kafka-code01.yml
      - conf/mybatis-plus.yml
      # - conf/mysql-yoga14s.yml
      - conf/maria-code01.yml
logging:
  level:
    org.zmz.b: debug
