spring:
  datasource:
    yoga14s:
      mysql:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/datacenter?serverTimezone=Asia/Shanghai
        username: root
        password: '123456'