spring:
  datasource:
    dataportal:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://172.21.72.158:5432/dataportal01?gssEncMode=disable&reWriteBatchedInserts=true
      username: postgres
      password: 'postgres'
