server:
  port: 9523
spring:
  application:
    name: micro-srv-c
  config:
    import:
      - conf/maria-local.yml
      - conf/pgsql-local.yml
      - conf/mysql-dev-dataopen-154.yml
      #- conf/mysql-dev-dataopen-156.yml
      #- conf/mysql-dev-dataportal-154.yml
      - conf/mysql-dev-dataportal-156.yml
      - conf/pgsql-dev.yml
      # - conf/redis-dev-154.yml
      - conf/redis-dev-156.yml
      # - conf/http2.yml
      - conf/kafka-code01.yml
      - conf/redisson-single-code01.yml
      - conf/spring-session.yml
logging:
  level:
    org.zmz.c: debug

management:
  health:
    db:
      enabled: off
