server:
  port: 9523
spring:
  application:
    name: micro-srv-c
  config:
    import:
      - conf/maria-local.yml
      - conf/pgsql-local.yml
      - conf/mysql-dev-dataopen.yml
      - conf/mysql-dev-dataportal.yml
      - conf/pgsql-dev.yml
logging:
  level:
    org.zmz.c: debug
