server:
  port: 9523
spring:
  application:
    name: micro-srv-c
  profiles:
    active: ${app.env:154}
  config:
    import:
      - conf/${spring.profiles.active}/dataportal.yml
      - conf/${spring.profiles.active}/dataopen.yml
      - conf/${spring.profiles.active}/redis.yml
      - conf/${spring.profiles.active}/redisson.yml
      - conf/${spring.profiles.active}/springsession.yml
logging:
  level:
    org.zmz.c: debug

management:
  health:
    db:
      enabled: off
