server:
  port: 9523
spring:
  application:
    name: micro-srv-c
  config:
    import:
      # - conf/kafka-code01.yml
      - conf/maria-local.yml
      - conf/pgsql-local.yml
logging:
  level:
    org.zmz.c: debug
