spring:
  datasource:
    mysql:
      dataopen:
        driverClassName: com.mysql.cj.jdbc.Driver
        #jdbcUrl: jdbc:mysql://172.21.72.155:8003/dataopen?serverTimezone=Asia/Shanghai
        #username: dataopen
        #password: 'dataopen'
        jdbcUrl: jdbc:mysql://172.21.72.155:8003/dataportal?serverTimezone=Asia/Shanghai
        username: dataportal
        password: 'dataportal'

mybatis:
  configuration:
    mysql:
      map-underscore-to-camel-case: on