spring:
  datasource:
    mysql:
      dev156:
        dataopen:
          driverClassName: com.mysql.cj.jdbc.Driver
          jdbcUrl: jdbc:mysql://172.21.72.157:8001/dataopen?serverTimezone=Asia/Shanghai
          username: root
          password: 'root'