spring:
  datasource:
    mysql:
      dev154:
        dataportal:
          driverClassName: com.mysql.cj.jdbc.Driver
          jdbcUrl: jdbc:mysql://172.21.72.155:8003/dataportal?serverTimezone=Asia/Shanghai
          username: root
          password: 'root'