spring:
  datasource:
    yoga14s:
      pgsql:
        driverClassName: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://localhost:5432/hrdb
        username: postgres
        password: '123456'